// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlitedb

import (
	"time"
)

type FileMeta struct {
	ID             string
	GraphID        string
	FileID         string
	BlobPath       string
	Checksum       []byte
	Size           int64
	LastModifiedAt time.Time
	LastModifiedTx int64
}

type Graph struct {
	ID        string
	Name      string
	CurrentTx int64
}

type GraphEncryptKey struct {
	ID                  string
	GraphID             string
	EncryptedPrivateKey string
	PublicKey           string
}

type GraphSalt struct {
	ID        string
	GraphID   string
	Value     []byte
	ExpiresAt time.Time
}
